@watchboarde_HostAddress = http://localhost:5178
@boardId = 57E35D12-0190-4F13-A72D-EB86C7126B5B
@listId = 3BB30402-919B-428A-9ADE-9C4E4EF434D8
@itemId = a5a1e706-dcfe-40fe-9777-307c83e20614

### Get all boards (ordered, with lists)
GET {{watchboarde_HostAddress}}/boards
Accept: application/json

### Get a board by ID (with lists)
GET {{watchboarde_HostAddress}}/boards/{{boardId}}
Accept: application/json

### Get a list by ID (with items)
GET {{watchboarde_HostAddress}}/lists/{{listId}}
Accept: application/json

### Get an item by GUID
GET {{watchboarde_HostAddress}}/items/{{itemId}}
Accept: application/json

### Get an item by TmDbId
GET {{watchboarde_HostAddress}}/items/ByTmDbId/100088
Accept: application/json

### Get poster for an item
GET {{watchboarde_HostAddress}}/items/{{itemId}}/poster

### Get backdrop for an item
GET {{watchboarde_HostAddress}}/items/{{itemId}}/backdrop

### Add TV show to a board
POST {{watchboarde_HostAddress}}/boards/{{boardId}}/tv/4551
Accept: application/json

### Add movie to a board
POST {{watchboarde_HostAddress}}/boards/{{boardId}}/movie/1233413
Accept: application/json

### Refresh an item by GUID
PUT {{watchboarde_HostAddress}}/items/{{itemId}}/refresh
Accept: application/json

### Delete item by GUID
DELETE {{watchboarde_HostAddress}}/items/5BEE1B6B-8BC6-4412-BA10-0CE019A62B87